spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:localhost;DB_CLOSE_ON_EXIT=FALSE
    continue-on-error: true
    username: admin
    password:
    
  jackson:
    serialization:
      write-dates-as-timestamps: false
